name: Build EPIC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ closed ]

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest  
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'

    - name: Build Windows binary
      run: |
        GOOS=windows GOARCH=amd64 go build -o EPIC.exe -ldflags "-w -s" -trimpath main.go

    - name: Build Linux binary
      run: |
        GOOS=linux GOARCH=amd64 go build -o EPIC-linux-amd64 -ldflags "-w -s" -trimpath main.go

    - name: Build macOS binary 
      run: |
        GOOS=darwin GOARCH=arm64 go build -o EPIC-darwin-arm64 -ldflags "-w -s" -trimpath main.go

    - name: List built binaries
      run: ls -la

    - name: Delete existing tag and release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete 1.0.2 --cleanup-tag --yes || echo "No release or tag found for 1.0.2"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 1.0.2
        release_name: EPIC 1.0.2
        body: |
          - Windows build (MSYS2) support fixed.
          - Better error message when required command is not found.
        draft: false          
        prerelease: false

    - name: Upload Windows asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: EPIC.exe
        asset_name: EPIC.exe
        asset_content_type: application/octet-stream

    - name: Upload Linux asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: EPIC-linux-amd64
        asset_name: EPIC-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload macOS asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: EPIC-darwin-arm64
        asset_name: EPIC-darwin-arm64
        asset_content_type: application/octet-stream